upstream vllm_cluster {
    server 100.108.245.77:9000;
    server 100.92.148.18:9000;
    server 100.112.76.83:9000;
    server 100.111.244.85:8080;
}

server {
    listen 8088;
    location / {
        proxy_pass http://vllm_cluster;
        proxy_read_timeout 120s;
        proxy_connect_timeout 10s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header X-Served-By $upstream_addr always;
    }
}
